# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSTestFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSTestFramework

  target 'iOSTestFrameworkTests' do
    # Pods for testing
  end

end
